changelog:
  categories:
    - title: 🏕 New Features
      labels:
        - feature
    - title: 🏋 Improvements
      labels:
        - fix
        - bug
    - title: 👒 Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - feature
          - fix
          - bug


